# File: .github/workflows/deploy-book.yml
name: Deploy Jupyter-Book to GitHub Pages

# grant contents write so the action can push
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install jupyter-book sphinx
      - run: jupyter-book build .
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          publish_branch: gh-pages
          allow_empty_commit: true
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
